#!/bin/sh

#
# Install the system in a partition
# * Check that the specified parm is a partition
# * Ask for "are you sure? Deleting everything"
# * Format vfat partition
# * syslinux -i /dev/mypartition
# * copy /cdrom in /mnt (or wherever)
# * umount ; sync
#
# Ref: https://wiki.ubuntu.com/LiveUsbPendrivePersistent
#
